substitutions:
  friendly_name: "Study Screens"

packages:
  device: !include common/devices/arlec1.yaml

# wifi:
#   manual_ip:
#     static_ip: "192.168.178.50"
#     gateway: "192.168.178.1"
#     subnet: "255.255.255.0"